name: .NET Core

on: [push]

jobs:
  build:
    name: Build application on ubuntu and windows
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build with dotnet
      run: | 
        cd src
        dotnet build --configuration Release
    - name: Build with node
      run: |
        cd src/ZerochSharp/ReactClient
        npm ci
        npm run build --prod

  test:
    name: Test application on ubuntu and windows
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Test with dotnet
        run: |
          cd src
          dotnet test
